namespace: 3-example
app:
  name: myapp
  image: panchanandevops/golang-fiber-app:0.0.5
  containerPort: 8080
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m
service:
  port: 8080
ingress:
  enabled: true
  className: nginx
  host: panchanandevops.com
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 80
  memoryUtilization: 70
